[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "braincoder"
version = "0.5.1"
description = "A modern neuroimaging modeling package"
authors = [
    {name = "Gilles de Hollander", email = "gilles.dehollander@gmail.com"}
]
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "keras>=3.0",
    "matplotlib",
    "seaborn",
    "pandas",
    "pandas_flavor",
    "scipy",
    "scikit-learn",
    "tqdm",
    "patsy",
]
readme = "README.md"
license = "MIT"

[project.optional-dependencies]
test = [
    "pytest",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["braincoder*"]
exclude = ["notebooks*"]

[tool.pytest.ini_options]
testpaths = ["tests"]